name: PR checks

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v2

      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
          output-file: README.md
          output-method: replace
          template: |-
            # Scheduled Vertex Pipelines

            This repo contains a Terraform module for scheduling a Vertex Pipeline using Google Cloud Scheduler, without the need for a Cloud Function or other "glue code".

            This module is available in the [Datatonic Terraform Registry](https://registry.terraform.io/namespaces/teamdatatonic).

            ## Limitations

            ### Pipeline job names

            Vertex Pipeline jobs created using the [Python SDK](https://github.com/googleapis/python-aiplatform) follow the format `<pipeline name>-<timestamp>`. This is implemented in the SDK itself (not by the API).
            Pipeline jobs created using this Terraform module instead just have the numeric ID as the job name. This is for two reasons:

            - The ability to specify the job name is only available in the gRPC API, not the HTTP API (Cloud Scheduler jobs can only target the HTTP API, not the gRPC API)
            - Regardless, Cloud Scheduler jobs cannot dynamically alter the HTTP payload based on a timestamp

            ### Caching

            Using the SDK, you can override the caching behavious for Vertex Pipeline steps. This feature is not available in the HTTP API used by this module.
            Instead, you can specify the caching behaviour in your actual pipeline definition.

            ## Development

            ### Local setup

            - Install [pre-commit](https://pre-commit.com/)
            - Install the pre-commit hooks - `pre-commit install`

            ### README

            The README file is autogenerated using [`terraform-docs`](https://github.com/terraform-docs/terraform-docs).

            You can customise the template (including this text for example) in `.terraform-docs.yml`.

            {{ .Content }}
          git-push: "true"
